imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "@ShopApiPlugin/Resources/config/app/config.yml" }


parameters:
    locale: en
    jwt_private_key_path: '%kernel.root_dir%/../../../../var/jwt/private.pem'
    jwt_public_key_path: '%kernel.root_dir%/../../../../var/jwt/public.pem'
    jwt_token_ttl: 3600
    secret: '%env(resolve:ECOMMERCE_SECRET)%'
    jwt_key_pass_phrase: '%env(resolve:ECOMMERCE_JWT_PASSPHRASE)%'
