framework:
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    form: true
    csrf_protection: true
    templating:
        engines: ["twig"]
    default_locale: "%locale%"
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../../../../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
