liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../../Ui/Http/Symfony/image"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../../Ui/Http/Symfony"
                cache_prefix: "media/cache"
