# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Beñat Espiña <benatespina@gmail.com>
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "@ShopApiPlugin/Resources/config/app/config.yml" }
    - { resource: ../../../../../parameters.yml }
    - { resource: security.yml }

parameters:
    locale: en
    jwt_private_key_path: '%kernel.root_dir%/../../../../var/jwt/private.pem'
    jwt_public_key_path: '%kernel.root_dir%/../../../../var/jwt/public.pem'
    jwt_token_ttl: 3600

framework:
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ["twig"]
    default_locale: "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../../../../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        server_version: "5.7"
        charset: UTF8

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../../Persistence/Doctrine/Migrations"
    namespace: ECommerce\Infrastructure\Persistence\Doctrine\Migrations
    table_name: migration_versions
    name: App migrations

accelerator_cache:
    host: "%router.request_context.scheme%://%router.request_context.host%"
    web_dir: "%kernel.root_dir%/../../Ui/Http/Symfony"

knp_gaufrette:
    adapters:
        sylius_image:
            local:
                directory: "%kernel.root_dir%/../../Ui/Http/Symfony/image"
                create: true

fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/shop-api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

nelmio_cors:
    paths:
        '^/shop-api/':
            allow_origin: ['.*\.shop.com', '.*\.lin3sdev.com', '^http://localhost:[0-9]+', '^http://192.168.[0-9]+.[0-9]+:[0-9]+']
            allow_methods: ['GET', 'POST', 'PUT']
            allow_headers: ['Content-Type', 'content-type', 'Authorization', 'authorization']
            max_age: 3600
            origin_regex: true

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../../Ui/Http/Symfony/image"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../../Ui/Http/Symfony"
                cache_prefix: "media/cache"
